# Generated by Django 3.1.7 on 2021-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
